version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://db/junidev
      - PORT=3000
    volumes:
      - /tmp/:/tmp/
    depends_on:
      - db
    db:
      image: mongo
      ports:
        - "27017:27017"
